server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: notification-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5437/notification_db}
    username: ${DB_USERNAME:notification_user}
    password: ${DB_PASSWORD:notification_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.PostgreSQLDialect # Removed to let Spring Boot auto-detect
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
        format_sql: true
    show-sql: true
  security:
    user:
      name: user
      password: password

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

# Security Configuration needed if relying on common-security or basic auth
jwt:
  secret: ${JWT_SECRET:2F423F4528482B4B6250655368566D5971337436763979244226452948404D6351}
