name: intelligent_financial_assistant_frontend
description: "A new Flutter project."
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  country_code_picker: ^3.4.1
  pin_code_fields: ^8.0.1
  google_sign_in: ^7.2.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  cloud_firestore: ^6.1.0
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  http: ^1.6.0
  get_it: ^9.0.5
  provider: ^6.1.5+1
  dropdown_search: ^6.0.2
  http_parser: ^4.1.2
  gradient_borders: ^1.0.2
  carousel_slider: ^5.1.1
  flutter_card_swiper: ^7.2.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/

  fonts:
    - family: SF-Pro-Rounded-Regular
      fonts:
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 600

